# SPDX-FileCopyrightText: 2023 2023 Kuropen <hy-kuropen@eternie-labs.net>
#
# SPDX-License-Identifier: CC0-1.0

name = "kporg-backend"
main = "src/index.ts"
compatibility_date = "2023-01-09"
account_id = "11b5327dbbe63a3113e9cc87c43a0ffd"

[[r2_buckets]]
binding = 'BLOG_BUCKET'
bucket_name = 'kuropen-blog-texts'
preview_bucket_name = 'kuropen-blog-texts'

[[ d1_databases ]]
binding = "DB"
database_name = "KPORG_BACKEND_DB"
database_id = "7052ec1f-9a6b-4a16-85ec-714aa61b78ff"

[triggers]
#crons = [ "0 17 * * *" ]
