name: Deploy backend (production)

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "apps/kporg-frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - name: Intalling dependencies
      run: yarn install
    - name: Deploy to Cloudflare Workers
      run: yarn backend.deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
